### ISSUE TITLE
dotenv error

### ISSUE THREAD

**Issue by jungbug** [jungbug/LostArk_exchange#5]
tsx에서 Env import 방법을 모르겠음 잘 안나옴 
그리고 인터넷에 있는 방법으로 호출하면 에러나옴

**Comment by sanghoon-chin** [comment]
### Solved

the commit [933e119](https://github.com/jungbug/LostArk_exchange/commit/933e1190ece29ea321ca1843f5e5890c324cf3c5) solved this issue

### How to use
1. `config/.base.env` 파일 복사해서 `config/.development.env` 파일 생성 후 원하는 값 추가
2. `webpack.config.js` 에서 DefinePlugin property에 string으로 추가 후 사용

**Comment by sanghoon-chin** [comment]
@jungbug
